import '@/assets/styles/globals.css'
import { Source_Code_Pro } from 'next/font/google'
import { Providers } from './providers'
import { Header, Footer } from '@/components'
import clsx from 'clsx'
import ProgressBar from '@/components/ProgressBar'

const sourceCodePro = Source_Code_Pro({
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  subsets: ['greek'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="zh-TW" suppressHydrationWarning>
      <title>Josh&apos;s blog</title>
      <body
        className={clsx(
          sourceCodePro.className,
          'min-h-screen flex flex-col bg-gray-100 dark:bg-slate-900'
        )}>
        <Providers>
          <Header />
          <ProgressBar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
