import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const Header = ({ ...rest }) => {
  return (
    <header {...rest}>
      <div className="flex justify-between p-6">
        <Link href="/">
          <h1>Josh&apos;s blog</h1>
        </Link>
        <p>🤟 Weclome to my blog. 💻</p>
      </div>
    </header>
  )
}

const Footer = ({ ...rest }) => {
  return (
    <footer {...rest}>
      <div>
        <br />
        <h3>Developed by Josh Hsu</h3>
      </div>
    </footer>
  )
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="zh-TW">
      <title>Josh&apos;s blog</title>
      <body
        className={inter.className}
        suppressHydrationWarning={true}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
