import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from './providers'
import { Header, Footer } from '@/components'
import clsx from 'clsx'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="zh-TW">
      <title>Josh&apos;s blog</title>
      <body
        className={clsx(inter.className, 'min-h-screen')}
        suppressHydrationWarning>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
